project:
  type: website

website:
  title: "MiniProject"
  navbar:
    left:
      - href: index.qmd
        text: Home


format:
  html:
    theme: cerulean
    css: styles.css
    toc: true
    code-fold: true
    embed-resources: true



